/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 10-Dec-2023 13:17:44 */
/* MATLAB Version: 9.6.0.1072779 (R2019a) */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef SBR1_FIS_H
#define SBR1_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void SBR1_init( void );
    void SBR1_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* SBR1_FIS_H */
